// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./array-form.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ArrayForm**
 * @see {@link ./array-form.as:3:18}
 */
export declare class ArrayForm {
  name: string
  tags: string[]
  scores: number[]
  addresses: {
    street: string
    city: string
    zip?: string
  }[]
  settings: {
    emailNotify: boolean /* checkbox */
    pageSize?: number
  }
  contacts: ({
    fullName: string
    email?: string /* email */
    phone?: string
  } | string)[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ArrayForm, ArrayForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ArrayForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end