// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./array-form.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ArrayForm**
 * @see {@link ./array-form.as:4:18}
 */
export declare class ArrayForm {
  // instructions: foorm.paragraph
  name: string
  tags: string[]
  scores: number[]
  addresses: Address[]
  settings: {
    emailNotify: boolean /* checkbox */
    pageSize?: number
  }
  contacts: ({
    fullName: string
    email?: string /* email */
    phone?: string
  } | string)[]
  category?: string /* select */
  // summary: foorm.paragraph
  // clearAction: foorm.action
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ArrayForm, ArrayForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ArrayForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **Address**
 * @see {@link ./array-form.as:99:11}
 */
declare class Address {
  street: string
  city: string
  zip?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address, Address>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Address>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript annotate **ArrayFormCustom**
 * @see {@link ./array-form.as:119:30}
 */
export declare class ArrayFormCustom extends ArrayForm {}
// prettier-ignore-end