// prettier-ignore-start
/* eslint-disable */
/// <reference path="./e2e-test-form.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **E2eTestForm**
 * @see {@link ./e2e-test-form.as:4:18}
 */
export declare class E2eTestForm {
  // info: foorm.paragraph
  firstName: string
  lastName: string
  age: number
  email?: string
  nickname?: string
  password: string
  secretCode?: string
  hiddenField?: string
  disabledField?: string
  styledField?: string
  // resetAction: foorm.action
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof E2eTestForm, E2eTestForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof E2eTestForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end