// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./exploration.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **TAddress**
 * @see {@link ./exploration.as:6:11}
 */
declare class TAddress {
  street: string
  city: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof TAddress, TAddress>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TAddress>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}

/**
 * Atscript interface **ExplorationForm**
 * @see {@link ./exploration.as:17:18}
 */
export declare class ExplorationForm {
  name: string
  addresses: TAddress[]
  contacts: {
    phone: string
  }[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ExplorationForm, ExplorationForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ExplorationForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end