// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./nested-form.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **NestedForm**
 * @see {@link ./nested-form.as:3:18}
 */
export declare class NestedForm {
  companyName: string
  address: {
    street: string
    city: string
    zip: string
    country: {
      name: string
      code: string
    }
  }
  contact: {
    firstName: string
    lastName?: string
    email?: string /* email */
    department: {
      name?: string
      floor?: number
      room?: string
    }
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof NestedForm, NestedForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof NestedForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end