// prettier-ignore-start
/* eslint-disable */
/// <reference path="./registration.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **RegistrationForm**
 * @see {@link ./registration.as:4:18}
 */
export declare class RegistrationForm {
  info: string /* paragraph */
  firstName: string
  lastName: string
  age: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof RegistrationForm, RegistrationForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof RegistrationForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
export declare namespace RegistrationForm {
  type DataType = RegistrationForm
}

// prettier-ignore-end