// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./simple-form.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **SimpleForm**
 * @see {@link ./simple-form.as:4:18}
 */
export declare class SimpleForm {
  title: string[]
  content: string
  complex: [string, boolean, string] | Address | string[][]
  test?: string[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SimpleForm, SimpleForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SimpleForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}

/**
 * Atscript interface **Address**
 * @see {@link ./simple-form.as:17:11}
 */
declare class Address {
  street: string
  city: string
  country: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address, Address>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Address>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end