// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    "meta.label": string
    "meta.id": string | true
    "meta.description": string
    "meta.documentation": (string)[]
    "meta.placeholder": string
    "meta.sensitive": boolean
    "meta.readonly": boolean
    "meta.isKey": boolean
    "expect.minLength": number
    "expect.maxLength": number
    "expect.min": number
    "expect.max": number
    "expect.int": boolean
    "expect.pattern": ({ pattern: string, flags?: string, message?: string })[]
    "emit.jsonSchema": boolean
    "foorm.title": string
    "foorm.submit.text": string
    "foorm.type": string
    "foorm.component": string
    "foorm.autocomplete": string
    "foorm.altAction": string
    "foorm.value": string
    "foorm.order": number
    "foorm.hidden": boolean
    "foorm.disabled": boolean
    "foorm.validate": (string)[]
    "foorm.fn.title": string
    "foorm.fn.submit.text": string
    "foorm.fn.submit.disabled": string
    "foorm.fn.label": string
    "foorm.fn.description": string
    "foorm.fn.hint": string
    "foorm.fn.placeholder": string
    "foorm.fn.disabled": string
    "foorm.fn.hidden": string
    "foorm.fn.optional": string
    "foorm.fn.classes": string
    "foorm.fn.styles": string
    "foorm.fn.options": string
    "meta.hint": string
  }
  type AtscriptPrimitiveTags = "never" | "string" | "email" | "phone" | "date" | "isoDate" | "uuid" | "number" | "positive" | "negative" | "single" | "double" | "int" | "timestamp" | "boolean" | "true" | "false" | "null" | "void" | "undefined" | "phantom" | "foorm" | "action" | "paragraph"
}
// prettier-ignore-end